config/routes.rb
AnagramSolver::Application.routes.draw do

  match 'logout' => 'login#logout', :as => 'logout'
  match 'login' => 'login#index', :as => 'login'
  match 'authenticate' => 'login#authenticate', :as => 'authenticate'

  get 'home/words', to: 'home#anagram_word_lookup', defaults: { format: 'json' }, as: 'anagram'
  match 'home' => 'home#index', as: 'home'
  
  root :to => 'login#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :user_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  def authenticate_user!
  	redirect_to login_path unless session[:user_id]
  end

  def current_user
  	 return @current_user ||= User.find(session[:user_id]) if session[:user_id]
  	 nil
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  before_filter :authenticate_user!
  
  def index
  end

  def anagram_word_lookup

    @word = params[:anagram][:word]
    @anagram = Anagram.new
    @results = @anagram.get_anagram @word

    respond_to do |format|
      format.html
      format.json{ render json: @results.to_json }
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  skip_before_filter :authenticate_user!
  
  def index
  	# default login screen
  end

  def authenticate
  	 
  	 @user = User.find_by_user_name_and_password(params[:user][:user_name], params[:user][:password])

     respond_to do |format|
     	 if @user
     	   session[:user_id] = @user.id
     	   format.html{ redirect_to home_path }
       else
          format.html{ redirect_to logout_path }
       end
     end
     
  end

  def logout
  	session.delete :user_id 
    redirect_to login_path
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		return @current_user = User.find(session[:user_id]) if session[:user_id].present?
		nil
	end

	def html(&block)
    	surround(%Q(<!--[if lt IE 7 ]><html lang="#{ I18n.locale }" class="no-js ie6"><![endif]--><!--[if IE 7 ]><html lang="#{ I18n.locale }" class="no-js ie7"><![endif]--><!--[if IE 8 ]><html lang="#{ I18n.locale }" class="no-js ie8"><![endif]--><!--[if IE 9 ]><html lang="#{ I18n.locale }" class="no-js ie9"><![endif]--><!--[if (gt IE 9)|!(IE)]> ><! <![endif]--><html class="no-js" lang="en" xml:lang="#{ I18n.locale }" xmlns='http://www.w3.org/1999/xhtml'><!-- <![endif] -->).html_safe, '</html>'.html_safe, &block)
    end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.haml
%main
  .content
    .control-group
      =form_for 'anagram', {url: anagram_path, method: 'get', remote: true , html: {'data-type' => 'json' } } do |f|
        .control-group
          =f.text_field 'word', :required => 'true', placeholder: 'search term', 'x-moz-errormessage' => 'Required search term'
          =f.submit 'Find anagrams', class: 'btn btn-primary btn-sm'

        .control-group
          #results          

app/views/layouts/application.html.haml
!!! 5
=html do
  %title Anagram solver...
  %head
  
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    
    #logo-ball{title: 'Solving the anogram...'}

    %nav.navbar.navbar-fixed-top{role: 'navigation'}
      .navbar-header.pull-left
        -if current_user
          .navbar-brand.logo
            Anagram solver
        
      -if current_user
        .navbar-collapse
          .row-fluid.header-row2.login-bar.pull-right
            %fieldset.login
              =link_to 'Logout', logout_path

      =render :partial => '/shared/login'
    
    -if current_user.nil?
      %header    
        .row 
          %h1.top
            Anagram solver

    -if current_user        
      .container
        .jumbotron
          =yield

app/views/login/authenticate.html.haml
%h1 Login#authenticate
%p Find me in app/views/login/authenticate.html.haml

app/views/login/index.html.haml
=render :partial => '/shared/login'

app/views/login/logout.html.haml
%h1 Login#logout
%p Find me in app/views/login/logout.html.haml

app/views/shared/_login.html.haml
- if current_user.nil?
  .navbar-collapse
    .row-fluid.header-row2.login-bar.pull-right
      %fieldset.login

        =form_for 'user', {url: authenticate_path} do |f|
          =f.text_field :user_name, placeholder: 'user name', type: 'text'
          =f.text_field :password, placeholder: 'password', type: 'password'
          =f.submit 'Login', class: 'btn btn-primary submit-login'

app/views/shared/_user_nav.html.haml
#main-navigation
  %ul.nav.nav-pills.header-nav
    %div.navbar.navbar-fixed-top
      .navbar-inner
        .container.logo
          .nav.pull-left
            %ul 
              %li 
                %h5
                  Anagram solver...                  

          .nav.pull-right
            %ul.nav
              %li
                %a{:href=>logout_page_path} logout